// Mocks generated by Mockito 5.4.6 from annotations
// in pratikapp/test/firebase/auth/firebase_auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_facebook_auth/flutter_facebook_auth.dart' as _i4;
import 'package:flutter_facebook_auth_platform_interface/flutter_facebook_auth_platform_interface.dart'
    as _i2;
import 'package:google_sign_in/google_sign_in.dart' as _i3;
import 'package:google_sign_in_platform_interface/google_sign_in_platform_interface.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLoginResult_0 extends _i1.SmartFake implements _i2.LoginResult {
  _FakeLoginResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoogleSignInAuthentication_1 extends _i1.SmartFake
    implements _i3.GoogleSignInAuthentication {
  _FakeGoogleSignInAuthentication_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FacebookAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockFacebookAuth extends _i1.Mock implements _i4.FacebookAuth {
  @override
  _i5.Future<_i2.AccessToken?> get accessToken => (super.noSuchMethod(
        Invocation.getter(#accessToken),
        returnValue: _i5.Future<_i2.AccessToken?>.value(),
        returnValueForMissingStub: _i5.Future<_i2.AccessToken?>.value(),
      ) as _i5.Future<_i2.AccessToken?>);

  @override
  bool get isWebSdkInitialized => (super.noSuchMethod(
        Invocation.getter(#isWebSdkInitialized),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<bool> get isAutoLogAppEventsEnabled => (super.noSuchMethod(
        Invocation.getter(#isAutoLogAppEventsEnabled),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i2.LoginResult> expressLogin() => (super.noSuchMethod(
        Invocation.method(
          #expressLogin,
          [],
        ),
        returnValue: _i5.Future<_i2.LoginResult>.value(_FakeLoginResult_0(
          this,
          Invocation.method(
            #expressLogin,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.LoginResult>.value(_FakeLoginResult_0(
          this,
          Invocation.method(
            #expressLogin,
            [],
          ),
        )),
      ) as _i5.Future<_i2.LoginResult>);

  @override
  _i5.Future<Map<String, dynamic>> getUserData(
          {String? fields = 'name,email,picture.width(200)'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserData,
          [],
          {#fields: fields},
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> logOut() => (super.noSuchMethod(
        Invocation.method(
          #logOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.LoginResult> login({
    List<String>? permissions = const [
      'email',
      'public_profile',
    ],
    _i2.LoginBehavior? loginBehavior = _i2.LoginBehavior.nativeWithFallback,
    _i2.LoginTracking? loginTracking = _i2.LoginTracking.limited,
    String? nonce,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #permissions: permissions,
            #loginBehavior: loginBehavior,
            #loginTracking: loginTracking,
            #nonce: nonce,
          },
        ),
        returnValue: _i5.Future<_i2.LoginResult>.value(_FakeLoginResult_0(
          this,
          Invocation.method(
            #login,
            [],
            {
              #permissions: permissions,
              #loginBehavior: loginBehavior,
              #loginTracking: loginTracking,
              #nonce: nonce,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.LoginResult>.value(_FakeLoginResult_0(
          this,
          Invocation.method(
            #login,
            [],
            {
              #permissions: permissions,
              #loginBehavior: loginBehavior,
              #loginTracking: loginTracking,
              #nonce: nonce,
            },
          ),
        )),
      ) as _i5.Future<_i2.LoginResult>);

  @override
  _i5.Future<void> webAndDesktopInitialize({
    required String? appId,
    required bool? cookie,
    required bool? xfbml,
    required String? version,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #webAndDesktopInitialize,
          [],
          {
            #appId: appId,
            #cookie: cookie,
            #xfbml: xfbml,
            #version: version,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> autoLogAppEventsEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #autoLogAppEventsEnabled,
          [enabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [GoogleSignIn].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignIn extends _i1.Mock implements _i3.GoogleSignIn {
  @override
  _i6.SignInOption get signInOption => (super.noSuchMethod(
        Invocation.getter(#signInOption),
        returnValue: _i6.SignInOption.standard,
        returnValueForMissingStub: _i6.SignInOption.standard,
      ) as _i6.SignInOption);

  @override
  List<String> get scopes => (super.noSuchMethod(
        Invocation.getter(#scopes),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  bool get forceCodeForRefreshToken => (super.noSuchMethod(
        Invocation.getter(#forceCodeForRefreshToken),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Stream<_i3.GoogleSignInAccount?> get onCurrentUserChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onCurrentUserChanged),
        returnValue: _i5.Stream<_i3.GoogleSignInAccount?>.empty(),
        returnValueForMissingStub: _i5.Stream<_i3.GoogleSignInAccount?>.empty(),
      ) as _i5.Stream<_i3.GoogleSignInAccount?>);

  @override
  _i5.Future<_i3.GoogleSignInAccount?> signInSilently({
    bool? suppressErrors = true,
    bool? reAuthenticate = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInSilently,
          [],
          {
            #suppressErrors: suppressErrors,
            #reAuthenticate: reAuthenticate,
          },
        ),
        returnValue: _i5.Future<_i3.GoogleSignInAccount?>.value(),
        returnValueForMissingStub: _i5.Future<_i3.GoogleSignInAccount?>.value(),
      ) as _i5.Future<_i3.GoogleSignInAccount?>);

  @override
  _i5.Future<bool> isSignedIn() => (super.noSuchMethod(
        Invocation.method(
          #isSignedIn,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i3.GoogleSignInAccount?> signIn() => (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
        ),
        returnValue: _i5.Future<_i3.GoogleSignInAccount?>.value(),
        returnValueForMissingStub: _i5.Future<_i3.GoogleSignInAccount?>.value(),
      ) as _i5.Future<_i3.GoogleSignInAccount?>);

  @override
  _i5.Future<_i3.GoogleSignInAccount?> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<_i3.GoogleSignInAccount?>.value(),
        returnValueForMissingStub: _i5.Future<_i3.GoogleSignInAccount?>.value(),
      ) as _i5.Future<_i3.GoogleSignInAccount?>);

  @override
  _i5.Future<_i3.GoogleSignInAccount?> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i5.Future<_i3.GoogleSignInAccount?>.value(),
        returnValueForMissingStub: _i5.Future<_i3.GoogleSignInAccount?>.value(),
      ) as _i5.Future<_i3.GoogleSignInAccount?>);

  @override
  _i5.Future<bool> requestScopes(List<String>? scopes) => (super.noSuchMethod(
        Invocation.method(
          #requestScopes,
          [scopes],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> canAccessScopes(
    List<String>? scopes, {
    String? accessToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #canAccessScopes,
          [scopes],
          {#accessToken: accessToken},
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [GoogleSignInAccount].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockGoogleSignInAccount extends _i1.Mock
    implements _i3.GoogleSignInAccount {
  @override
  String get email => (super.noSuchMethod(
        Invocation.getter(#email),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#email),
        ),
        returnValueForMissingStub: _i7.dummyValue<String>(
          this,
          Invocation.getter(#email),
        ),
      ) as String);

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
        returnValueForMissingStub: _i7.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  _i5.Future<_i3.GoogleSignInAuthentication> get authentication =>
      (super.noSuchMethod(
        Invocation.getter(#authentication),
        returnValue: _i5.Future<_i3.GoogleSignInAuthentication>.value(
            _FakeGoogleSignInAuthentication_1(
          this,
          Invocation.getter(#authentication),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.GoogleSignInAuthentication>.value(
                _FakeGoogleSignInAuthentication_1(
          this,
          Invocation.getter(#authentication),
        )),
      ) as _i5.Future<_i3.GoogleSignInAuthentication>);

  @override
  _i5.Future<Map<String, String>> get authHeaders => (super.noSuchMethod(
        Invocation.getter(#authHeaders),
        returnValue: _i5.Future<Map<String, String>>.value(<String, String>{}),
        returnValueForMissingStub:
            _i5.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i5.Future<Map<String, String>>);

  @override
  _i5.Future<void> clearAuthCache() => (super.noSuchMethod(
        Invocation.method(
          #clearAuthCache,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [GoogleSignInAuthentication].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignInAuthentication extends _i1.Mock
    implements _i3.GoogleSignInAuthentication {}
