// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9PI49OtHFucbIvETm2NJbPJxsMYWT7WQ',
    appId: '1:157264766220:web:1f3eb47fb87b2cde0d5529',
    messagingSenderId: '157264766220',
    projectId: 'improvevocabulary-d4181',
    authDomain: 'improvevocabulary-d4181.firebaseapp.com',
    storageBucket: 'improvevocabulary-d4181.firebasestorage.app',
    measurementId: 'G-CVFZKXGW9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoGTrsNjO697PXNu7AG5d1D-jEaoWT5b8',
    appId: '1:157264766220:android:3d6b01a7716059e90d5529',
    messagingSenderId: '157264766220',
    projectId: 'improvevocabulary-d4181',
    storageBucket: 'improvevocabulary-d4181.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVADmp3DLW_ycWTmeYX5uhoRw7Lz1vkus',
    appId: '1:157264766220:ios:1e5f16f82c065fe20d5529',
    messagingSenderId: '157264766220',
    projectId: 'improvevocabulary-d4181',
    storageBucket: 'improvevocabulary-d4181.firebasestorage.app',
    iosBundleId: 'com.example.pratikapp',
  );
}
