// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9PI49OtHFucbIvETm2NJbPJxsMYWT7WQ',
    appId: '1:157264766220:web:1f3eb47fb87b2cde0d5529',
    messagingSenderId: '157264766220',
    projectId: 'improvevocabulary-d4181',
    authDomain: 'improvevocabulary-d4181.firebaseapp.com',
    storageBucket: 'improvevocabulary-d4181.firebasestorage.app',
    measurementId: 'G-CVFZKXGW9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChURZ92RZU4sv-3Q5z00jJ5Bxf6eZXAhU',
    appId: '1:192901392737:android:cc0be71e8e8c8fd49a7d20',
    messagingSenderId: '192901392737',
    projectId: 'savgolearnvocabulary',
    storageBucket: 'savgolearnvocabulary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWpEYez6XQdPqZ4ipGmyYwnH69au-_HZI',
    appId: '1:192901392737:ios:9d200c2bf667ae4e9a7d20',
    messagingSenderId: '192901392737',
    projectId: 'savgolearnvocabulary',
    storageBucket: 'savgolearnvocabulary.firebasestorage.app',
    iosBundleId: 'com.furtem.savgolearnvocabulary',
  );

}